import { PropertyType, TransactionType } from './properties';

export interface NeighborhoodPrice {
  id: string;
  neighborhoodId: string;
  neighborhoodName: string;
  cityId: string;
  cityName: string;
  propertyType: PropertyType;
  transactionType: TransactionType;
  avgPrice: number;
  avgPricePerSqm: number;
  minPrice: number;
  maxPrice: number;
  sampleSize: number;
  year: number;
  quarter: number;
}

export const NEIGHBORHOOD_PRICES: NeighborhoodPrice[] = [
  {
    id: '1',
    neighborhoodId: '1',
    neighborhoodName: 'Cocody',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 95000000,
    avgPricePerSqm: 270000,
    minPrice: 65000000,
    maxPrice: 180000000,
    sampleSize: 24,
    year: 2025,
    quarter: 1,
  },
  {
    id: '2',
    neighborhoodId: '1',
    neighborhoodName: 'Cocody',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 420000,
    avgPricePerSqm: 3500,
    minPrice: 250000,
    maxPrice: 800000,
    sampleSize: 45,
    year: 2025,
    quarter: 1,
  },
  {
    id: '3',
    neighborhoodId: '3',
    neighborhoodName: 'Marcory',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 320000,
    avgPricePerSqm: 2800,
    minPrice: 180000,
    maxPrice: 600000,
    sampleSize: 38,
    year: 2025,
    quarter: 1,
  },
  {
    id: '4',
    neighborhoodId: '3',
    neighborhoodName: 'Marcory',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 55000000,
    avgPricePerSqm: 180000,
    minPrice: 35000000,
    maxPrice: 85000000,
    sampleSize: 18,
    year: 2025,
    quarter: 1,
  },
  {
    id: '5',
    neighborhoodId: '2',
    neighborhoodName: 'Plateau',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'COMMERCE',
    transactionType: 'LOCATION',
    avgPrice: 1200000,
    avgPricePerSqm: 12000,
    minPrice: 600000,
    maxPrice: 2500000,
    sampleSize: 32,
    year: 2025,
    quarter: 1,
  },
  {
    id: '6',
    neighborhoodId: '2',
    neighborhoodName: 'Plateau',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'BUREAU',
    transactionType: 'LOCATION',
    avgPrice: 1800000,
    avgPricePerSqm: 9000,
    minPrice: 900000,
    maxPrice: 3500000,
    sampleSize: 28,
    year: 2025,
    quarter: 1,
  },
  {
    id: '7',
    neighborhoodId: '4',
    neighborhoodName: 'Yopougon',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 220000,
    avgPricePerSqm: 1800,
    minPrice: 120000,
    maxPrice: 400000,
    sampleSize: 52,
    year: 2025,
    quarter: 1,
  },
  {
    id: '8',
    neighborhoodId: '4',
    neighborhoodName: 'Yopougon',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 35000000,
    avgPricePerSqm: 140000,
    minPrice: 20000000,
    maxPrice: 55000000,
    sampleSize: 31,
    year: 2025,
    quarter: 1,
  },
  {
    id: '9',
    neighborhoodId: '10',
    neighborhoodName: 'Bingerville',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'TERRAIN',
    transactionType: 'VENTE',
    avgPrice: 18000000,
    avgPricePerSqm: 35000,
    minPrice: 10000000,
    maxPrice: 35000000,
    sampleSize: 21,
    year: 2025,
    quarter: 1,
  },
  {
    id: '10',
    neighborhoodId: '10',
    neighborhoodName: 'Bingerville',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 42000000,
    avgPricePerSqm: 160000,
    minPrice: 28000000,
    maxPrice: 70000000,
    sampleSize: 15,
    year: 2025,
    quarter: 1,
  },
  {
    id: '11',
    neighborhoodId: '6',
    neighborhoodName: 'Treichville',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 280000,
    avgPricePerSqm: 2400,
    minPrice: 150000,
    maxPrice: 500000,
    sampleSize: 41,
    year: 2025,
    quarter: 1,
  },
  {
    id: '12',
    neighborhoodId: '6',
    neighborhoodName: 'Treichville',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'COMMERCE',
    transactionType: 'LOCATION',
    avgPrice: 850000,
    avgPricePerSqm: 8500,
    minPrice: 400000,
    maxPrice: 1800000,
    sampleSize: 26,
    year: 2025,
    quarter: 1,
  },
  {
    id: '13',
    neighborhoodId: '7',
    neighborhoodName: 'Koumassi',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'LOCATION',
    avgPrice: 240000,
    avgPricePerSqm: 1400,
    minPrice: 150000,
    maxPrice: 380000,
    sampleSize: 36,
    year: 2025,
    quarter: 1,
  },
  {
    id: '14',
    neighborhoodId: '7',
    neighborhoodName: 'Koumassi',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 180000,
    avgPricePerSqm: 1600,
    minPrice: 100000,
    maxPrice: 300000,
    sampleSize: 47,
    year: 2025,
    quarter: 1,
  },
  {
    id: '15',
    neighborhoodId: '13',
    neighborhoodName: 'Riviera Palmeraie',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 110000000,
    avgPricePerSqm: 300000,
    minPrice: 75000000,
    maxPrice: 200000000,
    sampleSize: 16,
    year: 2025,
    quarter: 1,
  },
  {
    id: '16',
    neighborhoodId: '14',
    neighborhoodName: 'Riviera Golf',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 135000000,
    avgPricePerSqm: 320000,
    minPrice: 90000000,
    maxPrice: 250000000,
    sampleSize: 12,
    year: 2025,
    quarter: 1,
  },
  {
    id: '17',
    neighborhoodId: '15',
    neighborhoodName: 'Deux Plateaux',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'APPARTEMENT',
    transactionType: 'LOCATION',
    avgPrice: 480000,
    avgPricePerSqm: 4000,
    minPrice: 300000,
    maxPrice: 900000,
    sampleSize: 38,
    year: 2025,
    quarter: 1,
  },
  {
    id: '18',
    neighborhoodId: '16',
    neighborhoodName: 'Angré',
    cityId: '1',
    cityName: 'Abidjan',
    propertyType: 'MAISON',
    transactionType: 'VENTE',
    avgPrice: 88000000,
    avgPricePerSqm: 250000,
    minPrice: 60000000,
    maxPrice: 150000000,
    sampleSize: 19,
    year: 2025,
    quarter: 1,
  },
];

export const getNeighborhoodPrices = (
  neighborhoodId: string,
  propertyType?: PropertyType,
  transactionType?: TransactionType
): NeighborhoodPrice[] => {
  return NEIGHBORHOOD_PRICES.filter((price) => {
    if (price.neighborhoodId !== neighborhoodId) return false;
    if (propertyType && price.propertyType !== propertyType) return false;
    if (transactionType && price.transactionType !== transactionType) return false;
    return true;
  });
};

export const getAvgPriceByNeighborhood = (
  neighborhoodId: string,
  propertyType: PropertyType,
  transactionType: TransactionType
): number | null => {
  const prices = getNeighborhoodPrices(neighborhoodId, propertyType, transactionType);
  if (prices.length === 0) return null;
  return prices[0].avgPrice;
};
